### ISSUE TITLE
Crashing with CircuitPython 7.3.3

### ISSUE THREAD

**Issue by g2rHP7prvJqO** [notnavindu/adafruit-macropad-hotkeys-with-extensions#2]
Hi,
I did a clean fresh install after UF2 nuke of adafruit-circuitpython-adafruit_macropad_rp2040-en_GB-7.3.3
I then installed the contents of this repo and nothing else.
It fails to load any of the bongo or pomodoro macros with a crash.
This is what I get in teh REPL:
Traceback (most recent call last):
  File "code.py", line 159, in <module>
  File "code.py", line 59, in switch
TypeError: function takes 2 positional arguments but 3 were given

I also get this:
ERROR in bongo.py
Traceback (most recent call last):
  File "code.py", line 125, in <module>
  File "code.py", line 47, in __init__
KeyError: custom_data

It seems like you need to add the data argument to the line 73 of pomodoro:
def Pomodoro(data, macropad, encoder_position):

For bongo, just create an empty data and do the same line 109:
def Loop(data, macropad, encoder_position):

**Comment by notnavindu** [comment]
Hey, sorry for getting back extremely late, I just saw this. I will look into this issue
